services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-app-python:3.13
    container_name: 
    command: sleep infinity
    volumes:
      - .:/app:z
      - venv_data:/app/.venv
    environment:
      - UV_LINK_MODE=copy
    userns_mode: keep-id

volumes:
  venv_data:

